language: generic
sudo: required
dist: trusty
compiler: gcc

branches:
  only:
  - all-platform-ci
  - "/^release.*$/"

env:
- PLATFORM=appliance
- PLATFORM=genericx86-64
- PLATFORM=as5712
- PLATFORM=as6712
- PLATFORM=as7512
- PLATFORM=as7712
- PLATFORM=mlnx-sn2xxx
  #- PLATFORM=as5812t
  #- PLATFORM=as5812x

addons:
  ssh_known_hosts: yocto.libreswitch.org

before_install:
- sudo apt-get update -qq
- sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib  build-essential chrpath screen curl device-tree-compiler libsdl1.2-dev xterm libfontconfig1
- sudo apt-get autoremove
install: true

script:
- travis_wait 50 make configure $PLATFORM
- travis_wait 50 make kernel
- travis_wait 50 make bake RECIPE="glibc"
- travis_wait 50 make bake RECIPE="python"
  #- travis_wait 50 make bake RECIPE="ops-quagga"
- travis_wait 50 make fs
- travis_wait 50 make

before_deploy:
- openssl aes-256-cbc -K $encrypted_2b923ab06c69_key -iv $encrypted_2b923ab06c69_iv
  -in tools/ci/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/build/sstate-cache/ && rsync -avzL --progress ?? universal libreswitch-ci@yocto.libreswitch.org:/data/yocto-cache/sstate-cache/
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a392ac25d47cc2eaf127
  on_success: change
  on_failure: always
  on_start: never

after_failure:
- df -h
- du -sh /home/travis/build/vitalivanov/libreswitch/build/downloads
- du -sh /home/travis/build/vitalivanov/libreswitch/build/tmp
- du -sh /home/travis/build/vitalivanov/libreswitch/build/sstate-cache
- du -sh /home/travis/build/vitalivanov/libreswitch/build
- ls -la /home/travis/build/vitalivanov/libreswitch/build/
