language: c
sudo: required
dist: trusty
compiler: gcc

branches:
  only:
  - all-platform-ci
  - "/^release.*$/"

env:
- PLATFORM=appliance
- PLATFORM=as5712
- PLATFORM=as5812t
- PLATFORM=as5812x
- PLATFORM=as6712
- PLATFORM=as7512
- PLATFORM=as7712
- PLATFORM=mlnx-sn2xxx
- PLATFORM=genericx86-64

addons:
  ssh_known_hosts: yocto.libreswitch.org

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq gawk wget git-core diffstat unzip texinfo build-essential
  chrpath screen curl device-tree-compiler
install: true

script:
- travis_wait 120 make configure $PLATFORM
- travis_wait 120 make kernel
- travis_wait 120 make

before_deploy:
- openssl aes-256-cbc -K $encrypted_2b923ab06c69_key -iv $encrypted_2b923ab06c69_iv
  -in tools/ci/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/build/sstate-cache/ && rsync -avzL --progress ?? universal libreswitch-ci@yocto.libreswitch.org:/data/yocto-cache/sstate-cache/
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a392ac25d47cc2eaf127
  on_success: change
  on_failure: always
  on_start: never
